### ISSUE TITLE
Handle `group` in properties

### ISSUE THREAD

**Issue by LastSprint** [surfstudio/SurfGen#21]
At this moment SurfGen can't handle case when `group` is declared under a property.

For example:
```YAML
AnyObject:
  type: object
  properties:
    anyProperty:
      oneOf:
        - $ref: "..."
```

This case won't be handled but seems like that we should be
