### ISSUE TITLE
Handle array inside `group`

### ISSUE THREAD

**Issue by LastSprint** [surfstudio/SurfGen#22]
At this moment SurfGen will throw error when `group` has array.

For example:

```YAML
WebSocketServerEvent:
  oneOf:
    - type: array
       items:
         $ref: '../common/models.yaml#/components/schemas/Identifier'
```

Seems like that we can generate code for this case
