### ISSUE TITLE
Invalid example config

### ISSUE THREAD

**Issue by NullIsOne** [surfstudio/SurfGen#41]
In root directory we have https://github.com/surfstudio/SurfGen/blob/master/example.config.yaml

But this config can't generate valid services because Entry missed.

Updating config to

```
templates:
  - type: service
    nameSuffix: Service
    fileExtension: swift
    templatePath: ./Templates/Swift/Service.txt
    destinationPath: ./trash/Sources/Services/{name}

  - type: model
    nameSuffix: Entity
    fileExtension: swift
    templatePath: ./Templates/Swift/Entity.txt
    destinationPath: ./trash/Sources/Models/{name}

  - type: model
    nameSuffix: Entry
    fileExtension: swift
    templatePath: ./Templates/Swift/Entry.txt
    destinationPath: ./trash/Sources/Models/{name}

  - type: enum
    fileExtension: swift
    fileNameCase: snakeCase
    templatePath: ./Templates/Swift/Entity.txt
    destinationPath: ./trash/Sources/Models/{name}

analytcsConfig:
    logstashEnpointURI: http://127.0.0.1:6644
    payload:
        project: Test
```

is solving problem.

But maybe it is unfair that only Swift has example configurations inside repo..
