### ISSUE TITLE
Enum of Int not parsed properly

### ISSUE THREAD

**Issue by NullIsOne** [surfstudio/SurfGen#42]
## Given

Repo:  https://github.com/surfstudio/ci-system-swagger

somewhere in `notifications/models.yaml`
```
AlertsType:
      type: integer
      enum: [1,2,3]
      description:  |
        Тип передачи уведомления:
        - 1 - выкл
        - 2 - push
        - 3 - sms 
      example: 3
```

config for generate Swift models and services

```
templates:
  - type: service
    nameSuffix: Service
    fileExtension: swift
    templatePath: ./Templates/Swift/Service.txt
    destinationPath: ./trash/Sources/Services/{name}

  - type: model
    nameSuffix: Entity
    fileExtension: swift
    templatePath: ./Templates/Swift/Entity.txt
    destinationPath: ./trash/Sources/Models/{name}

  - type: model
    nameSuffix: Entry
    fileExtension: swift
    templatePath: ./Templates/Swift/Entry.txt
    destinationPath: ./trash/Sources/Models/{name}

  - type: typealias
    nameSuffix: Entry
    fileExtension: swift
    templatePath: ./Templates/Swift/Typealias.txt
    destinationPath: ./trash/Sources/Models/{name}

  - type: enum
    fileExtension: swift
    fileNameCase: snakeCase
    templatePath: ./Templates/Swift/Enum.txt
    destinationPath: ./trash/Sources/Models/{name}
```
Templates from `v2/Swift`

## Expected result

Swift enum

```
/// Тип передачи уведомления:
///        - 1 - выкл
///        - 2 - push
///        - 3 - sms
public enum AlertsType: Int, Codable {
    case off = 1
    case push = 2
    case sms = 3
}
```

## Fact result

typealias

```
public typealias AlertsType = Int
```
