### ISSUE TITLE
Found in-place enums with lint command

### ISSUE THREAD

**Issue by NullIsOne** [surfstudio/SurfGen#43]
## Given

Repo:  https://github.com/surfstudio/ci-system-swagger

somewhere in `notifications/models.yaml`
```
Alert:
      type: object
      properties:
        notificationId:
          type: string           
          description: Идентификатор оповещения
          example: "2"  
        date:
          description: Дата оповещения
          $ref: "../common/models.yaml#/components/schemas/DateTime"  
        isRead:
          type: boolean           
          description: Прочитано оповещение или нет
          example: false
        notificationName:             
          type: string          
          description: Название оповещения
          example: "Пожар"
        id:
          type: string
          description: Идентификатор ОА к которому относится оповещение
          example: "111"
        name:
          type: string
          description: Название ОА к которому относится оповещение
          example: "ГБУЗ 'МО Солнечногорская ЦРБ'"
        notificationType:
          type: string
          enum: [incidentInfo, callsControlInfo, unassignedEmergencyInfo, notFreeAmbulamceInfo]
          description:  |
              Тип оповещения:
                - incidentInfo - происшествие
                - callsControlInfo - вызов на контроле
                - unassignedEmergencyInfo - экстренный вызов не назначен вовремя
                - notFreeAmbulamceInfo - нет свободных бригад
          example: "incidentInfo"
        additionalInfo:
          $ref: "models.yaml#/components/schemas/AdditionalInfo"          

```

## Expected result

`surfgen lint` failed 

## Fact result

`surfgen lint` succeed
