### ISSUE TITLE
Show error for unsupported references to operations or models

### ISSUE THREAD

**Issue by margarita-v** [surfstudio/SurfGen#76]
If swagger has features which are not supported yet:
```
paths:
  /auth/login:
    $ref: "./auth/auth_login.yml"

schemas:
    $ref: "./definitions.yml"
```
than `surfGen lint` command will be successful anyway (probably because linter has an empty list of operations and finishes successfully). But `surfGen generate` command fails with `[1]  90705 trace trap` error.
It would be great if SurfGen showed the detailed error message for this unsupported case, because currently it is not obvious and seems to be wrong
